export * from './Admin'
export { default as Capacitaciones } from './Capacitaciones'
export { default as Contacto } from './Contacto'
export { default as Inicio } from './Inicio'
export { default as Productos } from './Productos'
export { default as Servicios } from './Servicios'
export { default as Somos } from './Somos'
